# Site settings
title: Cohere Pledge
subtitle: A barebone GitHub Pages with static comments
email: interactive@cohere.city
description: Test
baseurl: "pledge/"
url: "https://cohere-city.github.io"
locale: en
github_username:  Cohere-city

# Build settings
markdown: kramdown

staticman:
  api: "https://staticman3.herokuapp.com/v3/entry/github/cohere-city/pledge/master/comments"
  path: "_data/comments/test-slug"
